model_builder/logistic_build/urls.py
from django.urls import path
from django_filters.views import FilterView
from . import views
from .models import ExperimentFilter

# app_name="logistic_build"
urlpatterns = [
    path('', views.index, name='index'),
    path('upload/csv', views.upload_csv, name='upload_csv'),
    path('traindata', views.TraindataListView.as_view(), name='traindata_list'),
    path('traindata/<int:pk>/detail', views.TraindataDetailView.as_view(), name='traindata_detail'),
    path('traindata/create/', views.TraindataCreateView.as_view(), name='traindata_create'),
    path('traindata/<int:pk>/update/', views.TraindataUpdateView.as_view(), name='traindata_update'),
    path('traindata/<int:pk>/delete/', views.TraindataDeleteView.as_view(), name='traindata_delete'),
    
    # path('experiment', views.ExperimentListView.as_view(), name='experiment_all'),
    # path("experiment/", FilterView.as_view(filterset_class=ExperimentFilter), name="experiment-list"),
    path("experiment/", views.experiment_list, name="experiment-list"),
    path('experiment/<int:pk>/detail', views.ExperimentDetailView.as_view(), name='experiment_detail'),
    path('experiment/create/', views.ExperimentCreateView.as_view(), name='experiment_create'),
    # path('experiment/start/', views.experiment_start, name='experiment_start'),
    path('experiment/start/', views.ExperimentFormView.as_view(), name='experiment_form'),
    path('experiment/<int:pk>/update/', views.ExperimentUpdateView.as_view(), name='experiment_update'),
    path('experiment/<int:pk>/delete/', views.ExperimentDeleteView.as_view(), name='experiment_delete'),

    path('stationarity', views.StationarityListView.as_view(), name='stationarity_all'),
    path('stationarity/<int:pk>/detail', views.StationarityDetailView.as_view(), name='stationarity_detail'),
    path('stationarity/create/', views.StationarityCreateView.as_view(), name='stationarity_create'),
    path('stationarity/<int:pk>/update/', views.StationarityUpdateView.as_view(), name='stationarity_update'),
    path('stationarity/<int:pk>/delete/', views.StationarityDeleteView.as_view(), name='stationarity_delete'),

    path('variables/<int:experiment_id>', views.VariablesListView.as_view(), name='variables'),
    path('variables/<int:pk>/detail', views.VariablesDetailView.as_view(), name='variables_detail'),
    path('variables/create/', views.VariablesCreateView.as_view(), name='variables_create'),
    path('variables/<int:pk>/update/', views.VariablesUpdateView.as_view(), name='variables_update'),
    path('variables/<int:pk>/delete/', views.VariablesDeleteView.as_view(), name='variables_delete'),
    
    path('manualvariableselection', views.ManualvariableselectionListView.as_view(), name='all'),
    path('manualvariableselection/<int:pk>/detail', views.ManualvariableselectionDetailView.as_view(), name='manualvariableselection_detail'),
    path('manualvariableselection/create/', views.ManualvariableselectionCreateView.as_view(), name='manualvariableselection_create'),
    path('manualvariableselection/<int:pk>/update/', views.ManualvariableselectionUpdateView.as_view(), name='manualvariableselection_update'),
    path('manualvariableselection/<int:pk>/delete/', views.ManualvariableselectionDeleteView.as_view(), name='manualvariableselection_delete'),
    
    path('classificationmodel', views.ClassificationmodelListView.as_view(), name='all'),
    path('classificationmodel/<int:pk>/detail', views.ClassificationmodelDetailView.as_view(), name='classificationmodel_detail'),
    # path('classificationmodel/create/', views.ClassificationmodelCreateView.as_view(), name='classificationmodel_create'),
    path('classificationmodel/<int:topmodel_id>/create/', views.ClassificationmodelCreateView.as_view(), name='classificationmodel_create'),
    path('classificationmodel/create/', views.ClassificationmodelCreateView.as_view(), name='classificationmodel_create_scratch'),

    path('classificationmodel/<int:pk>/update/', views.ClassificationmodelUpdateView.as_view(), name='classificationmodel_update'),
    path('classificationmodel/<int:pk>/delete/', views.ClassificationmodelDeleteView.as_view(), name='classificationmodel_delete'),
    path('index_j/', views.index_j, name='index_j'),
    path('resultsclassificationmodel/<int:pk>/detail', views.ResultsClassificationmodelDetailView.as_view(), name='resultsclassificationmodel_detail'),
    # path('resultsclassificationmodel/<int:pk>/detail', views.ResultsClassificationmodelDetailView.as_view(), name='resultsclassificationmodel_detail'),
    path('register/', views.register_user,name='register'),
    path('regressionmodel/<int:pk>/detail', views.RegressionmodelDetailView.as_view(), name='regressionmodel_detail'),
    path('regressionmodel/create/', views.RegressionmodelCreateView.as_view(), name='regressionmodel_create'),
    path('regressionmodel/<int:pk>/update/', views.RegressionmodelUpdateView.as_view(), name='regressionmodel_update'),
    path('regressionmodel/<int:pk>/delete/', views.RegressionmodelDeleteView.as_view(), name='regressionmodel_delete'),

    path('notificationmodelbuild', views.NotificationModelBuildListView.as_view(), name='notificationmodelbuild'),
    path('notificationmodelbuild/<int:pk>/update/', views.NotificationModelBuildUpdateView.as_view(), name='notificationmodelbuild_update'),
    path('notificationmodelbuild/delete/', views.notifications_delete, name='notificationmodelbuild_delete'),
    path('notificationmodelbuild/mark_as_read', views.notifications_mark_as_read, name='notificationmodelbuild_markasread')  ,
    path('featureselection/<int:pk>/detail', views.FeatureselectionDetailView.as_view(), name='featureselection_detail'),
    path('featureselection/create/', views.FeatureselectionCreateView.as_view(), name='featureselection_create'),
    path('featureselection/<int:pk>/update/', views.FeatureselectionUpdateView.as_view(), name='featureselection_update'),
    path('featureselection/<int:pk>/delete/', views.FeatureselectionDeleteView.as_view(), name='featureselection_delete'),
    path('resultsfeatureselection/<int:pk>/detail', views.ResultsFeatureselectionDetailView.as_view(), name='resultsfeatureselection_detail'),
]

model_builder/model_builder/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
        path('logistic_build/', include('logistic_build.urls')),
    path('admin/', admin.site.urls),
    
]
admin.site.site_header = 'Model Builder Administration'                    # default: "Django Administration"
admin.site.index_title = 'Model Builder'                 # default: "Site administration"
admin.site.site_title = 'Model builder site admin' # default: "Django site admin"


urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    # path('logistic_build/', include('logistic_build.urls',namespace='logistic_build')),
]

model_builder/logistic_build/models.py
import django_filters
from django.db import models
import json

from django.urls import reverse

from .utils import get_spark_session
# Create your models here.
from .stationarity_tests import adfuller_test, kpss_test
import pandas as pd
from django.core.files.storage import default_storage
import os
from django_q.tasks import async_task
from datetime import datetime
from django.conf import settings
from pathlib import Path
from django.utils import timezone
from django.contrib.auth.models import User
import os
import glob
import datatable as dt

import shortuuid

class Traindata(models.Model):
    file_id = models.AutoField(primary_key=True)
    train_data_name = models.CharField(max_length=100, null=True, blank=True)
    train_path = models.CharField(max_length=50)
    no_of_cols = models.IntegerField(null=True, blank=True)
    no_of_rows = models.IntegerField(null=True, blank=True)
    column_names = models.CharField(max_length=50, null=True, blank=True)
    # colnames = models.CharField(max_length=54)
    # relevant_col_names = models.CharField(max_length=500)

    def get_absolute_url(self):
        return reverse('traindata_detail', args=[str(self.file_id)])
    # def set_relevant_col_names(self, x):
    #     self.relevant_col_names = json.dumps(x)

    # def get_relevant_col_names(self):
    #     return json.loads(self.relevant_col_names)

    # def get_col_names(self):
    #     return json.loads(self.colnames)
    def __str__(self):
        return self.train_data_name if self.train_data_name else ''

    def get_fields(self):
        return [(field.verbose_name, field.value_from_object(self)) for field in self.__class__._meta.fields[1:]]

    def save(self, *args, **kwargs):

        # if file details are already available, there is no need to re-read these details
        # file details are available in case of spark operations, where output file is written by spark
        # in case the file is directly input via the front end, this infor will be missing and hence will have to be read in the save here
        if not self.no_of_cols:
            if os.path.isdir(self.train_path):
                # Path can be a directory in case it has multiple files. Usually this willbe because these are csv files from a spark write operation
                # for now it is assumed that these are all csv files and spark will be used to read these files
                pass
            else:
                t = dt.fread(file=self.train_path)
                self.no_of_cols = list(t.shape)[1]
                self.no_of_rows = list(t.shape)[0]
                self.column_names = json.dumps(list(t.names))
        super(Traindata, self).save(*args, **kwargs)


class Experiment(models.Model):

    class Meta:
        ordering = ['-created_on_date']
    EXPERIMENT_TYPE = [
        ('input', 'Input'),
        ("columnformatchange", 'Column format change'),
        ('featureengineering', 'Feature engineering'),
        ('stationarity', 'Stationarity test'),
        ('manualvariableselection', 'Manual variable selection'),
        ('featureselection', 'Feature Selection'),
        ('classificationmodel', 'Build logistic regression model'),
        ('regressionmodel', 'Build regression model')
    ]
    STATUS_TYPE = [("NOT_STARTED", "NOT STARTED"), ("STARTED", "STARTED"), ("IN_PROGRESS", "IN PROGRESS"), ("DONE", "DONE"), ("ERROR", "ERROR")]
    experiment_id = models.AutoField(primary_key=True)
    experiment_type = models.CharField(max_length=100, choices=EXPERIMENT_TYPE, null=True, blank=True, default="input")
    name = models.CharField(max_length=100)
    artefacts_directory = models.CharField(max_length=100, null=True, blank=True)
    # start_date = models.DateField(null=True, blank=True)
    created_on_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    experiment_status = models.CharField(max_length=20, choices=STATUS_TYPE, null=True, blank=True)
    traindata = models.ForeignKey(Traindata, on_delete=models.CASCADE, null=True, blank=True, related_name='input_train_data')
    testdata = models.ForeignKey(Traindata, on_delete=models.CASCADE, null=True, blank=True, related_name='input_test_data')
    do_create_data = models.BooleanField(default=True)
    output_data = models.ForeignKey(Traindata, on_delete=models.CASCADE, null=True, blank=True, related_name='output_data')
    previous_experiment = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
    run_now = models.BooleanField(default=False)
    lock_now = models.BooleanField(default=False)
    run_start_time = models.DateTimeField(null=True, blank=True)
    run_end_time = models.DateTimeField(null=True, blank=True)
    created_by = models.ForeignKey(User,
                                   null=True, blank=True, on_delete=models.CASCADE)
    run_in_the_background = models.BooleanField(default=False)
    enable_spark = models.BooleanField(default=False)
    all_preceding_experiments = models.TextField(max_length=20000, blank=True, null=True)
    train_data_saved = models.ForeignKey(Traindata, on_delete=models.CASCADE, null=True, blank=True, related_name='train_data_split_randomly')
    test_data_saved = models.ForeignKey(Traindata, on_delete=models.CASCADE, null=True, blank=True, related_name='test_data_split_randomly')
    test_flag = models.BooleanField(default=False, null = True, blank=True, editable=False)

    def _track_precedents(self):
        if self.previous_experiment:
            if self.previous_experiment.all_preceding_experiments:
                prev_exp_dict = json.loads(self.previous_experiment.all_preceding_experiments)
                prev_exp_dict.append((self.previous_experiment.experiment_id, self.previous_experiment.experiment_type, self.previous_experiment.name))
                # prev_exp_dict[self.experiment_id]= f"{self.experiment_type}:{self.exeriment_name}"
                self.all_preceding_experiments = json.dumps(prev_exp_dict)
            else:
                prev_exp_dict = [(self.previous_experiment.experiment_id, self.previous_experiment.experiment_type, self.previous_experiment.name)]
                self.all_preceding_experiments = json.dumps(prev_exp_dict)

    def __str__(self):
        return self.name if self.name else ''

    def get_fields(self):
        return [(field.verbose_name, field.value_from_object(self)) for field in self.__class__._meta.fields[1:]]

    def get_fields_by_type(self,type):
        # Helper function to categorise fields by type
        about_ = ["name", "experiment_type", "created_on_date", "created_by"]
        model_parameters_ = ["traindata", "testdata", "train_split", "test_split", "cross_validation", "label_col", "feature_cols", "ignored_columns"]
        run_details_ = ["run_in_the_background", "enable_spark", "save_train_test_data"]
        results_ = ["experiment_status", "run_start_time", "run_end_time", 'train_data_saved','test_data_saved','results']
        field_type_dict = {'about': about_,'model_parameters': model_parameters_,'run_details':run_details_,'results':results_   }
        fields_list_ordered=[]

        for field_name in field_type_dict[type]:
            for f in self.__class__._meta.fields[1:]:
                if f.name == field_name:
                    fields_list_ordered.append(f)
                    break
            pass
        fields = [(field.verbose_name, field.value_from_object(self)) for field in fields_list_ordered]
        return fields
            
        # return [(field.verbose_name, field.value_from_object(self)) for field in self.__class__._meta.fields[1:]]
    def get_fields_by_type_about(self):
        return self.get_fields_by_type('about')
    def get_fields_by_type_model_parameters(self):
        return self.get_fields_by_type('model_parameters')
    def get_fields_by_type_run_details(self):
        return self.get_fields_by_type('run_details')
    def get_fields_by_type_results(self):
        return self.get_fields_by_type('results')
    

    def get_absolute_url(self):
        if self.experiment_type != 'input':
            return reverse(f'{self.experiment_type}_detail', args=[str(self.experiment_id)])
        else:
            return reverse('experiment_detail', args=[str(self.experiment_id)])

    def save(self, *args, **kwargs):
        print(kwargs)
        self._track_precedents()
        super(Experiment, self).save(*args, **kwargs)
        # super(Experiment, self).save(*args, **kwargs)
        if not self.artefacts_directory:
            self.artefacts_directory = os.path.join("artefacts", "experiment_"+str(self.experiment_id)+"_"+self.name)
            os.makedirs(self.artefacts_directory, exist_ok=True)
            kwargs['force_insert'] = False
            super(Experiment, self).save(*args, **kwargs)


class Variables(models.Model):
    MODEL_VARIABLE_TYPE = [
        ('Dependent', 'Dependent'),
        ('Independent', 'Independent'),
    ]
    EXPERIMENT_STATUS_TYPE = [
        ('PASS', 'PASS'),
        ('FAIL', 'FAIL'),
    ]
    variable_id = models.AutoField(primary_key=True)
    variable_name = models.CharField(max_length=100, null=True, blank=True)
    traindata = models.ForeignKey(Traindata, on_delete=models.SET_NULL, blank=True, null=True)
    experiment = models.ForeignKey(Experiment, on_delete=models.SET_NULL, null=True)
    variable_type = models.CharField(
        max_length=20,
        choices=MODEL_VARIABLE_TYPE,
        default='Independent',
    )
    experiment_status = models.CharField(
        max_length=20,
        choices=EXPERIMENT_STATUS_TYPE,
        default='FAIL',
    )

    def __str__(self):
        return self.variable_name

    def get_fields(self):
        return [(field.verbose_name, field.value_from_object(self)) for field in self.__class__._meta.fields[1:]]

    def get_absolute_url(self):
        return reverse('variables_detail', args=[str(self.variable_id)])


class Stationarity(Experiment):
    do_kpss = models.BooleanField(default=False)

model_builder/logistic_build/templates/logistic_build/experiment_detail.html
{% extends 'logistic_build/index.html' %}

{% block  list_view_content%}

<div class="" style="width: 70%;">
    <div class="col">
        <h1 class="text-center">Experiment Details </h1>
        <div class="d-flex justify-content-center">
            <table class="table table-striped mt-5" style="width: 50%">
                <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                
                    {% for label, value in experiment.get_fields  %}
                    {% if not label == "colnames" %}
                        <tr>
                            <td>{{label | upper}}</td>
                            <td>{{value}}</td>
                        </tr>
                    {% endif %}
                    {% endfor %}
                        
                </tbody>
            </table>
            <p><strong>Experiment:</strong> <a href="{{ experiment.traindata.get_absolute_url }}">{{ experiment.traindata.train_path}}</a></p>


        </div>
<div>
</div>
        <div class="d-flex justify-content-center">
            <a href="{% url 'all' %}" class="d-block btn btn-primary btn-lg my-5">BACK</a>
        </div>
    </div>
        
</div>

{% endblock  %}

model_builder/logistic_build/templates/logistic_build/experiment_form.html
{% extends 'logistic_build/index.html' %}
{% load crispy_forms_tags %}
{% block  list_view_content%}

<!-- BOOTSTRAP FORM -->
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5>Hello card</h5>
                                        </div>
                                        <div class="card-block">
        
                                            <div class="container d-flex justify-content-center mt-5" style="width: 25%;">
                                                <form action="" method="post">
                                                    {% csrf_token %}
                                                    {{form|crispy}}
                                                    <table class="table">
                                                    </table>
                                                    <div class="container d-flex justify-content-center" style="width: 10%;">
                                                        <input type="submit" class="btn btn-primary btn-lg" value="SUBMIT" name="_initiation" style="margin-right: 30px; margin-top: 30px;">
                                                        <!-- <input type="submit" class="btn btn-primary btn-lg" value="SAVE AS DRAFT" name="_draft" style="margin-right: 30px; margin-top: 30px;"> -->
                                                        <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{% url "all" %}'; return false;" value="Cancel">
                                                    </div>    
                                                </form> 
                                                <div class="col mt-5">
                                            
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

<!-- END BOOTSTRAP FORM -->

{% endblock %}

model_builder/logistic_build/templates/logistic_build/featureselection_detail.html
{% extends 'logistic_build/index.html' %}
{% block  list_view_content%}



<div class="" style="width: 70%;">
    <div class="col">
        <h1 class="text-center">Regression model Details </h1>
        {% include 'logistic_build/includes/previous_experiments.html' %}
 

        <div class="d-flex justify-content-center">
            <table class="table-striped mt-5 stationarity_table" style="width: 100%; table-layout: fixed;    max-width: 600px;">
                <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>

                    {% for label, value in featureselection.get_fields  %}
                    {% if not label == "results" and not label == "created by"  %}
                        <tr>
                            <td>{{label | upper}}</td>
                            <td style="word-break:break-all;style=width: 50%">{{value}}</td>
                        </tr>
   
                    {% elif label == "results" %}
                        <tr>
                            <td>{{label | upper}}</td>
                            {% if value %}
                            <td style="word-break:break-all;style="width: 50%""><a href="{% url 'resultsfeatureselection_detail' value %}">View Results </a></td>
                            {% else %}
                            <td>None</td>
                            {% endif %}
                        </tr>
                    
                    {% endif %}


                    {% endfor %}
                        
                </tbody>
            </table>


        </div>
<div>
        <div class="d-flex justify-content-center">
            <a href="{% url 'featureselection_update' featureselection.experiment_id %}" class="d-block btn btn-primary btn-lg my-5">UPDATE / RE-RUN </a>

        </div>
        <div class="d-flex justify-content-center">
        </div>
    </div>
        
</div>

{% endblock  %}

model_builder/logistic_build/templates/logistic_build/fibonnaci_form-to-delete.html
{% extends 'logistic_build/index.html' %}

{% block  list_view_content%}

<!-- BOOTSTRAP FORM -->
<h1>Fibonacci Form</h1>
<div class="container d-flex justify-content-center mt-5" style="width: 25%;">
    <div class="col mt-5">
        <form action="" method="post">
            {% csrf_token %}
            <table class="table">
                {{form.as_table}}
            </table>
            <div class="container d-flex justify-content-center" style="width: 10%;">
                <input type="submit" class="btn btn-primary btn-lg" value="Submit" style="margin-right: 30px; margin-top: 30px;">
                <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{% url "all" %}'; return false;" value="Cancel">
            </div>    
        </form> 

    </div>
</div>

<!-- END BOOTSTRAP FORM -->

{% endblock %}

model_builder/logistic_build/templates/logistic_build/manualvariableselection_detail.html
{% extends 'logistic_build/index.html' %}

{% block  list_view_content%}

<div class="" style="width: 70%;">
    <div class="col">
        <h1 class="text-center">Variable Selection Tests model Details </h1>
        {% include 'logistic_build/includes/previous_experiments.html' %}

        <div class="d-flex justify-content-center">
            <table class="table-striped mt-5 stationarity_table" style="width: 100%; table-layout: fixed;    max-width: 600px;">
                <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>

                    {% for label, value in manualvariableselection.get_fields  %}
                    {% if not label == "colnames" and not label == "created by" %}
                        <tr>
                            <td>{{label | upper}}</td>
                            <td style="word-break:break-all;style="width: 50%"">{{value}}</td>
                        </tr>
                    {% endif %}

                    {% if label == "created by" %}
                    
                        <tr>
                            <td>{{label | upper}}</td>
                            <td style="word-break:break-all;style="width: 50%"">{{created_by}}</td>
                        </tr>
                    
                    {% endif %}
                    {% endfor %}
                        
                </tbody>
            </table>


        </div>
<div>
</div>
        <div class="d-flex justify-content-center">
            <a href="{% url 'all' %}" class="d-block btn btn-primary btn-lg my-5">BACK</a>
            {% comment %}
  <!-- <a href="{% url 'variables' experiment_id=manualvariableselection.experiment_id %}" class="d-block btn btn-primary btn-lg my-5">SHOW RESULTS</a> -->
{% endcomment %}
            <a href="{% url 'variables' experiment_id=manualvariableselection.experiment_id %}" class="d-block btn btn-primary btn-lg my-5">SHOW RESULTS</a>
        </div>
        <div class="d-flex justify-content-center">
        </div>
    </div>
        
</div>

{% endblock  %}

model_builder/logistic_build/templates/logistic_build/manualvariableselection_form.html
{% extends 'logistic_build/index.html' %}

{% block  list_view_content%}


<script type="text/javascript">
    train_data_dict = {{ train_data_dict|safe }};
</script>

    <!-- BOOTSTRAP FORM -->
    
<div class="container d-flex justify-content-center mt-5" style="width: 25%;">
    <div class="col mt-5">
<h4> Manual </h4>

        <form action="" method="post">
            {% csrf_token %}
            <table class="table">
                {{form.as_table}}
            </table>
            <div class="container d-flex justify-content-center" style="width: 10%;">
                                <input type="submit" class="btn btn-primary btn-lg" value="SUBMIT" name="_run_now" style="margin-right: 30px; margin-top: 30px;">
                <input type="submit" class="btn btn-primary btn-lg" value="SAVE AS DRAFT" name="_draft" id="_draft" style="margin-right: 30px; margin-top: 30px;">
                <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{% url "all" %}'; return false;" value="Cancel">
            </div>    
        </form> 

    </div>
</div>

  <div aria-live="polite" aria-atomic="true" style="min-height: 200px;">
    <div class="toast" style="position: absolute; bottom: 0; right: 0; z-index: 9999; float: right;" data-delay="10000">
      <div class="toast-header">
        <strong class="mr-auto">Model Builder</strong>
        <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="toast-body">
        Saved Manually Selected Variable as Draft!
      </div>
    </div>
  </div>
  


{% block javascripts %}
<!-- <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"/>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script> -->

    <script type="text/javascript">
        
        
        window.addEventListener('load', function() {
                            console.log("working");
    
                            $(".toast").toast('hide');
                            v=$('#id_traindata').val();
                            console.log(v);
                            if ($('#id_keep_columns').is(':empty')){
// if columns are pre-populated do not change. Change only if columns is empty, and if the 
                $('#id_keep_columns').html(train_data_dict[v]);
                    }
            $( "#id_traindata" ).change(function() {
                console.log("changed values");
                v=$('#id_traindata').val();
                console.log(train_data_dict[v]);
                $('#id_keep_columns').html(train_data_dict[v]);
            });

            $("#_draft").on('click', function(){
                    $(".toast").toast('show');
            });
        });
      

    </script>


        {% endblock %}
    

<!-- END BOOTSTRAP FORM -->

{% endblock %}

model_builder/logistic_build/templates/logistic_build/regressionmodel_form.html
{% extends 'logistic_build/index.html' %}
{% load crispy_forms_tags %}
{% block  list_view_content%}


<script type="text/javascript">
    train_data_dict = {{ train_data_dict|safe }};
</script>

    <!-- BOOTSTRAP FORM -->
    
<div class="container d-flex justify-content-center mt-5" style="width: 25%;">
    <div class="">

<h2> classification</h2>
        <form action="" method="post">
            {% csrf_token %}
            {{form | crispy }}

            <div class="container d-flex justify-content-center" style="width: 10%;">
                <input type="submit" class="btn btn-primary btn-lg" value="SUBMIT" name="_run_now" style="margin-right: 30px; margin-top: 30px;">
                <input type="submit" class="btn btn-primary btn-lg" value="SAVE AS DRAFT" name="_draft" style="margin-right: 30px; margin-top: 30px;">
                <input type="submit" class="btn btn-danger btn-lg" style="margin-top: 30px;" onclick="window.location='{% url "all" %}'; return false;" value="Cancel">
            </div>    
        </form> 

    </div>
</div>

{% block javascripts %}
    <script type="text/javascript">
        

        
        window.addEventListener('load', function() {

                            v=$('#id_traindata').val();
                            console.log(v);
                            $('#id_feature_cols').html(train_data_dict[v]);

            $( "#id_traindata" ).change(function() {
                console.log("changed values");
                v=$('#id_traindata').val();
                console.log(train_data_dict[v]);
                $('#id_feature_cols').html(train_data_dict[v]);
            });
        })
    </script>
        {% endblock %}
    

<!-- END BOOTSTRAP FORM -->

{% endblock %}